"""Render a volume page's panel placeholders and image briefs from volumes/<vol>-panels.json.

  python3 tools/volume_panels.py IV

Each panel sits in the page between <!-- PANEL <id> --> and <!-- /PANEL <id> --> markers (never hand-edit between
them). The full briefs (scene, Blender sites, cast, reference sheets, caption, notes) go to
prompts/volume-<vol>-panels.md, the input for image generation later.
"""
import html, json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SIZE = {"splash": "", "strip": "", "wide": "", "half": "mid", "tall": "narrow"}

def placeholder(p, shapes):
    esc = html.escape
    img = ROOT / "volumes" / "images" / f"{p['id']}.jpg"                                          # an accepted panel image replaces the placeholder
    if img.exists():
        inner = f'<img src="images/{img.name}" alt="{esc(p["title"])}: {esc(p["desc"])}" loading="lazy">'
    else:
        inner = (f'<div class="img-placeholder ph-{p["shape"]}" role="img" aria-label="{esc(p["title"])}: {esc(p["desc"])}">'
             f'<span class="ph-label">{p["id"]} · {shapes[p["shape"]]}</span>'
             f'<span class="ph-title">{esc(p["title"])}</span>'
             f'<span class="ph-desc">{esc(p["desc"])}</span>'
             f'<span class="ph-meta">Blender: {esc("; ".join(p["sites"]))} · Sheets: {esc(", ".join(p["refs"]))}</span></div>')
    attrs = f'data-panel="{p["id"]}" data-shape="{p["shape"]}" data-refs="{" ".join(p["refs"])}"'
    if p["shape"] == "splash":                                                                     # the cover frame
        return f'<div class="frame-cover" id="panel-{p["id"]}" {attrs}>{inner}</div>'
    cls = " ".join(c for c in ("panel", SIZE[p["shape"]], {"l": "tilt-l", "r": "tilt-r"}.get(p.get("tilt", ""), "")) if c)
    cap = f'\n    <figcaption>{esc(p["caption"])}</figcaption>' if p["caption"] else ""
    return f'<figure class="{cls}" id="panel-{p["id"]}" {attrs}>\n    <div class="frame">{inner}</div>{cap}\n  </figure>'

def main():
    vol = sys.argv[1]
    spec = json.loads((ROOT / "volumes" / f"{vol}-panels.json").read_text())
    page = ROOT / spec["page"]; text = page.read_text(); missing = []
    for p in spec["panels"]:
        a, b = f'<!-- PANEL {p["id"]} -->', f'<!-- /PANEL {p["id"]} -->'
        i, j = text.find(a), text.find(b)
        if i < 0 or j < i: missing.append(p["id"]); continue
        text = text[:i] + a + "\n  " + placeholder(p, spec["shapes"]) + "\n  " + text[j:]
    page.write_text(text)
    md = [f"# Volume {vol} panels", "",
          f"Generated by `tools/volume_panels.py {vol}` from `volumes/{vol}-panels.json`; edit the JSON, not this file. "
          "Each panel is drawn in the house style (see `references/README.md`), with no legible writing. Where a scene is set on the island, "
          "the Blender scene named under *Blender* is the reference for the architecture and the layout; the sheets are the reference for people and props. "
          "The canon wins over any sheet: every ledger is a parchment scroll on two rods, written like a log: one entry per line, each line "
          "parallel to the rods, entries running top to bottom with no side-by-side columns, and held open upright with one rod across the top and one across the bottom.", ""]
    for p in spec["panels"]:
        md += [f"## {p['id']} · {p['title']}", "", f"- **Shape:** {spec['shapes'][p['shape']]}", f"- **Blender:** {'; '.join(p['sites'])}",
               f"- **Cast:** {p['cast']}", f"- **Sheets:** {', '.join('`references/' + r + '.jpg`' for r in p['refs'])}"]
        if p["caption"]: md.append(f"- **Caption:** {p['caption']}")
        if p.get("notes"): md.append(f"- **Notes:** {p['notes']}")
        md += ["", p["scene"], ""]
    (ROOT / "prompts" / f"volume-{vol}-panels.md").write_text("\n".join(md))
    print(f"{len(spec['panels']) - len(missing)} panels rendered" + (f"; missing markers: {missing}" if missing else ""))

if __name__ == "__main__":
    main()
